<?php
return array(
	'title'         => esc_html__( 'Header Setting', 'foodchow' ),
	'id'            => 'header1_setting',
	'desc'          => '',
	'subsection'    => true,
	'fields'        => array(

		array(
			'id'                => 'header1_sticky',
			'type'              => 'switch',
			'title'     		=> esc_html__( 'Show Sticky Header', 'foodchow' ),
			'desc'      		=> esc_html__( 'Enable to show sticky Header.', 'foodchow' ),
		),
		array(
			'id'     			=> 'header1_topbar',
			'type'              => 'switch',
			'title'             => esc_html__( 'Header Top Bar', 'foodchow' ),
			'desc'              => esc_html__( 'Enable to show header top bar section.', 'foodchow' ),
		),
		array(
			'id'                => 'topbar1_settng',
			'type'              => 'section',
			'title'             => esc_html__( 'Top Bar Settings', 'foodchow' ),
			'desc'              => esc_html__( 'This section is used to set top bar.', 'foodchow' ),
			'required'          =>  array(
				array( 'header1_topbar','equals', true ),
			),
			'indent'            => true,
		),
		array(
			'id'     			=> 'topbar_menu',
			'type'              => 'switch',
			'title'             => esc_html__( 'Enable Top Bar Menu', 'foodchow' ),
			'desc'              => esc_html__( 'Enable to show header top bar menu.', 'foodchow' ),
		),
		array(
			'id'                => 'show_topbar_sharing',
			'type'              => 'switch',
			'title'             => esc_html__( 'Show Share Icon', 'foodchow' ),
			'desc'              => esc_html__( 'Enable to show top bar sharing icon', 'foodchow' ),

		),
	  	array(
			'id'       => 'topbar_social_share',
			'type'     => 'social_media',
            'title'    => esc_html__( 'Social Profiles', 'foodchow' ),
			'desc' 	   => esc_html__( 'Click an icon to activate social profile icons in top bar.', 'foodchow' ),
			'required' => array( 'show_topbar_sharing', '=', true ),
		),
		array(
			'id'    => 'show_topbar_login',
			'type'  => 'switch',
			'title' => esc_html__( 'Show Top Bar Login', 'foodchow' ),
			'desc'  => esc_html__( 'Enable to show login button in topbar.', 'foodchow' ),
		),
		array(
			'id'       => 'login_title',
			'type'     => 'text',
			'title'    => esc_html__( 'Login Label', 'foodchow' ),
			'desc'     => esc_html__( 'Enter login button label that you want to show.', 'foodchow' ),
			'required' => array( 'show_topbar_login', '=', true ),
			'default'  => esc_html__( 'Login', 'foodchow' ),
		),
	
		array(
			'id'               => 'login_link',
			'type'             => 'select',
			'data'             => 'pages',
			'title'            => esc_html__( 'Login Page', 'foodchow' ),
			'desc'             => esc_html__( 'Select login page.', 'foodchow' ),
			'required' => array( 'show_topbar_login', '=', true ),
		),
		array(
			'id'    => 'header1_cart',
			'type'  => 'switch',
			'title' => esc_html__( 'Show Cart', 'foodchow' ),
			'desc'  => esc_html__( 'Enable to show cart in header', 'foodchow' ),
		),
		array(
			'id'     => 'topbar1_setting_end',
			'type'   => 'section',
			'indent' => false,
		),
		array(
			'id'     => 'header1_logo',
			'type'   => 'section',
			'title'  => esc_html__( 'Logo Settings', 'foodchow' ),
			'desc' 	 => esc_html__( 'This section is used to set logo settings', 'foodchow' ),
			'indent' => true,
		),
		array(
			'id' 	  => 'logo1_type',
			'type' 	  => 'button_set',
			'title'   => esc_html__( 'Logo Style', 'foodchow' ),
			'desc' 	  => esc_html__( 'Select anyone logo style to show in header', 'foodchow' ),
			'options' => array(
				'image' => esc_html__( 'Image Logo', 'foodchow' ),
				'text'  => esc_html__( 'Text Logo', 'foodchow' ),
			),
			'default' 	=> 'image',
		),
		array(
			'id'       => 'image1_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Logo', 'foodchow' ),
			'subtitle' => esc_html__( 'Insert site logo image with adjustable size for the logo section', 'foodchow' ),
			'default'  => array( 'url'=> FOODCHOW_URL.'assets/images/logo.png' ),
			'required' =>  array( array( 'logo1_type','equals','image' ) ),
		),
		array(
			'id'       => 'logo1_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Logo Dimentions', 'foodchow' ),
			'subtitle' => esc_html__( 'Select Logo Dimentions', 'foodchow' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' =>  array(
                array( 'logo1_type','equals','image' ),
				array( 'custom_header', 'equals', 'header_1' ),
			),
		),
		array(
			'id'       => 'logo1_text',
			'type'     => 'text',
			'title'    => esc_html__( 'Logo Text', 'foodchow' ),
			'subtitle' => esc_html__( 'Enter Logo Text', 'foodchow' ),
			'required'   		=>  array(
				array( 'logo1_type','equals','text' ),
			),
		),
		array(
			'id'          => 'logo1_typography',
			'type'        => 'typography', 
			'title'       => esc_html__( 'Typography', 'foodchow' ),
			'google'      => true,
			'font-backup' => false,
			'text-align'  =>  false,
			'line-height' =>  false,
			'output'      => array( 'h2.site-description' ),
			'units'       =>'px',
			'subtitle'    => esc_html__( 'Select Styles for text logo', 'foodchow' ),
			'default'     => array(
				'color'       => '#333',
				'font-style'  => '700',
				'font-family' => 'Abel',
				'google'      => true,
				'font-size'   => '33px',
			),
			'required'    =>  array(
				array( 'logo1_type','equals','text' ),
				array( 'custom_header', 'equals', 'header_1' ),
			),
		),
		array(
			'id'     => 'header1_logo_end',
			'type' 	 => 'section',
			'indent' => false,
		),

		array(
			'id'    => 'show_logobar_phone',
			'type'  => 'switch',
			'title' => esc_html__( 'Show Logo Bar Phone Number', 'foodchow' ),
			'desc'  => esc_html__( 'Enable to show phone number in logobar.', 'foodchow' ),
		),
		array(
			'id'       => 'phone_title',
			'type'     => 'text',
			'title'    => esc_html__( 'Phone Title', 'foodchow' ),
			'desc'     => esc_html__( 'Enter phone number in logobar that you want to show.', 'foodchow' ),
			'required' => array( 'show_logobar_phone', '=', true ),
			'default'  => esc_html__( 'give us a call', 'foodchow' ),
		),
		array(
			'id'       => 'phone_num',
			'type'     => 'text',
			'title'    => esc_html__( 'Phone Title', 'foodchow' ),
			'desc'     => esc_html__( 'Enter phone title in logobar that you want to show.', 'foodchow' ),
			'required' => array( 'show_logobar_phone', '=', true ),
			'default'  => esc_html__( '( 800 ) 489 6589', 'foodchow' ),
		),
		array(
			'id'    => 'show_logobar_timing',
			'type'  => 'switch',
			'title' => esc_html__( 'Show Logo Bar Phone Timing', 'foodchow' ),
			'desc'  => esc_html__( 'Enable to show available timing in logobar.', 'foodchow' ),
		),
		array(
			'id'       => 'availble_title',
			'type'     => 'text',
			'title'    => esc_html__( 'Availble Time', 'foodchow' ),
			'desc'     => esc_html__( 'Enter availble time in logobar that you want to show.', 'foodchow' ),
			'required' => array( 'show_logobar_timing', '=', true ),
			'default'  => esc_html__( 'Mon-Fri : 9:00 AM TO 7:00 PM', 'foodchow' ),
		),
		array(
			'id'       => 'closed_day',
			'type'     => 'text',
			'title'    => esc_html__( 'Closed day', 'foodchow' ),
			'desc'     => esc_html__( 'Enter closed day that you want to show e.g  SUNDAY : CLOSED.', 'foodchow' ),
			'required' => array( 'show_logobar_timing', '=', true ),
			'default'  => esc_html__( 'SUNDAY : CLOSED', 'foodchow' ),
		),
		array(
			'id' 	=> 'header1_appointment',
			'type' 	=> 'switch',
			'title' => esc_html__( 'Show Appointment Button', 'foodchow' ),
			'desc' 	=> esc_html__( 'Enable to show appointment button in header', 'foodchow' ),
		),
		array(
			'id'         => 'menubar_bg_color',
			'type'       => 'color',
			'title'      => esc_html__( 'Menu Bar Background Color', 'foodchow' ),
			'default'    => '##2e8ece',
			'transparent' => false,
		),
		array(
			'id'       => 'appointment_label',
			'type'     => 'text',
			'title'    => esc_html__( 'Button Label', 'foodchow' ),
			'subtitle' => esc_html__( 'Enter button label to show.', 'foodchow' ),
			'required' =>  array(
				array( 'header1_appointment','equals', true ),
			),
		),
		array(
			'id'               => 'appointment1_page',
			'type'             => 'select',
			'data'             => 'pages',
			'title'            => esc_html__( 'Appointment Page', 'foodchow' ),
			'desc'             => esc_html__( 'Select appointment page.', 'foodchow' ),
			'required'         => array(
				array( 'header1_appointment','equals', true ),
			),
		),
	)
);
